language: node_js
sudo: false
node_js:
  - 6.2
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - "npm run coverage"
after_script:
  - greenkeeper-lockfile-upload
  - "./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info"
